import '@/styles/globals.css'
import { Poppins } from 'next/font/google'
 
const poppins = Poppins({
  weight: ['400','700'],
  subsets: ['latin'],
})
export const metadata = {
  title: 'Plearn',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  )
}
